/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BkButton: typeof import('./src/components/BkButton.vue')['default']
    BkCommentList: typeof import('./src/components/comment/BkCommentList.vue')['default']
    BkItext: typeof import('./src/components/BkItext.vue')['default']
    BkLoading: typeof import('./src/components/BkLoading.vue')['default']
    BkSvg: typeof import('./src/components/BkSvg.vue')['default']
    BkTab: typeof import('./src/components/BkTab.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAnchor: typeof import('element-plus/es')['ElAnchor']
    ElAnchorLink: typeof import('element-plus/es')['ElAnchorLink']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LzCanvas: typeof import('./src/components/LzCanvas.vue')['default']
    MdEditor: typeof import('./src/components/MdEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeView: typeof import('./src/components/TimeView.vue')['default']
    Vanta: typeof import('./src/components/Vanta.vue')['default']
    VideoPlayer: typeof import('./src/components/BkVideo/VideoPlayer.vue')['default']
    Wave: typeof import('./src/components/svg/Wave.vue')['default']
    WaveSurfer: typeof import('./src/components/WaveSurfer.vue')['default']
    WelcomeLog: typeof import('./src/components/WelcomeLog.vue')['default']
    WriteComment: typeof import('./src/components/comment/WriteComment.vue')['default']
  }
}
